# Generated by Django 4.2.7 on 2024-03-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="data",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="size",
            field=models.IntegerField(default=2),
        ),
    ]
