# Generated by Django 4.2.7 on 2024-03-09 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_userinfo_data_userinfo_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="data",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="size",
        ),
    ]
