# Generated by Django 4.2.7 on 2024-03-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP_manage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateField(verbose_name="入职时间"),
        ),
    ]
